# Copyright (c) 2020-present, The kubequery authors
#
# This source code is licensed as defined by the LICENSE file found in the
# root directory of this source tree.
#
# SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: cluster
    app.kubernetes.io/version: "1.0.0"
  name: kubequery

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubequery-sa
  namespace: kubequery

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubequery-clusterrole
rules:
- apiGroups: ["", "admissionregistration.k8s.io", "apps", "autoscaling", "batch", "events.k8s.io", "networking.k8s.io", "policy", "rbac.authorization.k8s.io", "storage.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubequery-clusterrolebinding
roleRef:
  kind: ClusterRole
  name: kubequery-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kubequery-sa
  namespace: kubequery

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubequery-config
  namespace: kubequery
data:
  osquery.flags: |
    # Update flags to suit your requirements
    --disable_memory=true
    --extensions_interval=5
    --extensions_timeout=5
    --watchdog_level=-1
    --verbose
  osquery.conf: |
    {
      "schedule": {
        "kubernetes_events": {
          "query": "SELECT * FROM kubernetes_events",
          "interval": 10
        },
        "kubernetes_namespaces": {
          "query": "SELECT * FROM kubernetes_namespaces",
          "interval": 600
        },
        "kubernetes_role_policy_rules": {
          "query": "SELECT * FROM kubernetes_role_policy_rules",
          "interval": 600
        },
        "kubernetes_cluster_role_policy_rules": {
          "query": "SELECT * FROM kubernetes_cluster_role_policy_rules",
          "interval": 600
        },
        "kubernetes_cluster_role_binding_subjects": {
          "query": "SELECT * FROM kubernetes_cluster_role_binding_subjects",
          "interval": 600
        },
        "kubernetes_pod_security_policies": {
          "query": "SELECT uid, cluster_uid, name, privileged, host_pid, host_ipc, host_network, allow_privilege_escalation, value AS 'run_as_user_rule' FROM kubernetes_pod_security_policies, json_tree(kubernetes_pod_security_policies.run_as_user) WHERE key = 'rule'",
          "interval": 600
        }
      },
      "options":{
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubequery
  name: kubequery
  namespace: kubequery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubequery
  template:
    metadata:
      labels:
        app: kubequery
    spec:
      hostname: my-cluster # TODO: Give a friendly cluster name
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      terminationGracePeriodSeconds: 10
      serviceAccountName: kubequery-sa
      containers:
        - name: kubequery
          image: uptycs/kubequery:0.1.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 200Mi
            requests:
              cpu: 500m
              memory: 200Mi
          volumeMounts:
          - name: config
            mountPath: /opt/kubequery/etc
      volumes:
      - name: config
        configMap:
          name: kubequery-config
